### ISSUE TITLE
GameFrameWork의 표기 문제에 대해

### ISSUE THREAD

**Issue by LusainKim** [KPU-WARP/winapi-framework#1]
Framework는 한 단어입니다. FrameWork는 두 단어를 붙여 쓴 것으로 착각할 수 있기에, GameFrameWork를 GameFramework로 수정하는 것을 건의합니다.

**Comment by GameForPeople** [comment]
선배님께서 예전에 저희 가르쳐주실때, 프레임워크는 한단어다! 딱 알려주셧는데, 깜빡했네요...대문자병...ㅠ 확인이 늦어 죄송합니다. 이번주 주말내로 전부 수정하도록 하겠습니다.

감사합니다. 선배님!

@LusainKim

**Comment by GameForPeople** [comment]
Commit ( 828b9ba )에서 수정하였습니다.
감사합니다. 도율 선배님! 👍 

https://github.com/KPU-WARP/winapi-framework/commit/828b9ba6b26e6166f93228deb8ca35af433fdeef
