### ISSUE TITLE
[알려진 이슈] Windows SDK 10 버전의 사용에 대하여

### ISSUE THREAD

**Issue by LusainKim** [KPU-WARP/winapi-framework#2]
알려진 이슈는 Windows SDK 10 버전을 사용하여 생기는 문제입니다. 레거시 SDK인 8.1을 두고, 사용자가 특정하여 설치하여야 하는 10 버전을 굳이 사용할 필요는 없을 것 같습니다.

Windos SDK 10 버전에서 Windows.h의 변경점이 거의 없으며, 본 repository에 굳이 Windows SDK 10 버전의 API가 필요한지에 대해서 의문을 제기합니다.

**Comment by GameForPeople** [comment]
선배님! 해당 이슈도, Commit ( 828b9ba )에서 수정하였습니다.
감사합니다! 

https://github.com/KPU-WARP/winapi-framework/commit/828b9ba6b26e6166f93228deb8ca35af433fdeef
